DROP SCHEMA TODO IF EXISTS;

CREATE SCHEMA TODO;

CREATE SEQUENCE TODO.s_todo_id START WITH 1;

CREATE TABLE TODO.todo (
  id INT NOT NULL,
  title VARCHAR(256) NOT NULL,
  is_complete BOOLEAN,
  ordering INT,

  CONSTRAINT pk_t_todo PRIMARY KEY (id)
);